---
# tasks file for JsirL.ansible-document-servers
- name: Deploying Template to Gather and Save info from Remote Systems
  ansible.builtin.template:
     src: rhel_managed_infra_report.j2
     dest: /root/hwreport.txt
     mode: preserve
